import sqlite3

# Hindi translations for all UI strings
# Format: {translation_key: hindi_text}
HI_TRANSLATIONS = {
    # Book authors
    "book.ananda-vrndavana-campu.author": "श्रील कवि कर्णपूर",
    "book.bhagavatam.author": "वेद व्यास",
    "book.bhakti-rasamrta-sindhu.author": "श्रील रूप गोस्वामी",
    "book.brhad-bhagavatamrta.author": "श्रील सनातन गोस्वामी",
    "book.caitanya-candramrta.author": "श्रील प्रबोधानन्द सरस्वती",
    "book.caitanya-candrodaya.author": "श्रील कवि कर्णपूर",
    "book.caitanya-carita.author": "श्रील मुरारि गुप्त",
    "book.caitanya-caritamrta-mahakavya.author": "श्रील कवि कर्णपूर",
    "book.caitanya-caritamrta.author": "श्रील कृष्णदास कविराज गोस्वामी",
    "book.dana-keli-kaumudi.author": "श्रील रूप गोस्वामी",
    "book.gita-govinda.author": "श्रील जयदेव गोस्वामी",
    "book.gopala-campu.author": "श्रील जीव गोस्वामी",
    "book.govinda-lilamrta.author": "श्रील विश्वनाथ चक्रवर्ती ठाकुर",
    "book.govinda-virudavali.author": "श्रील रूप गोस्वामी",
    "book.jagannatha-vallabha-nataka.author": "श्री रामानन्द राय",
    "book.krama-dipika.author": "श्री केशव काश्मीरी भट्ट",
    "book.krsna-bhavanamrta.author": "श्रील विश्वनाथ चक्रवर्ती ठाकुर",
    "book.krsna-karnamrta.author": "श्रील बिल्वमङ्गल ठाकुर (लीलाशुक)",
    "book.krsnahnika-kaumudi.author": "श्रील कवि कर्णपूर",
    "book.lalita-madhava.author": "श्रील रूप गोस्वामी",
    "book.padyavali.author": "श्रील रूप गोस्वामी",
    "book.radha-krsna-ganoddesa-dipika.author": "श्रील रूप गोस्वामी",
    "book.radha-rasa-sudha-nidhi.author": "श्रील प्रबोधानन्द सरस्वती",
    "book.sadhanamrta-candrika.author": "श्री सिद्ध कृष्णदास बाबाजी",
    "book.sangita-madhava.author": "श्री गोविन्द कविराज (गोविन्द दास)",
    "book.stavamala.author": "श्रील रघुनाथ दास गोस्वामी",
    "book.stavavali.author": "श्रील रघुनाथ दास गोस्वामी",
    "book.ujjvala-nilamani.author": "श्रील रूप गोस्वामी",
    "book.vidagdha-madhava.author": "श्रील रूप गोस्वामी",
    "book.vilapa-kusumanjali.author": "श्रील रघुनाथ दास गोस्वामी",
    "book.vraja-riti-cintamani.author": "श्रील विश्वनाथ चक्रवर्ती ठाकुर",
    "book.vrndavana-mahimamrta.author": "गौड़ीय परम्परा",

    # Book titles
    "book.ananda-vrndavana-campu.title": "आनन्दवृन्दावनचम्पू",
    "book.bhagavatam.title": "श्रीमद्भागवतम्",
    "book.bhakti-rasamrta-sindhu.title": "भक्तिरसामृतसिन्धु",
    "book.brhad-bhagavatamrta.title": "बृहद्भागवतामृत",
    "book.caitanya-candramrta.title": "चैत्यचन्द्रामृत",
    "book.caitanya-candrodaya.title": "चैत्यचन्द्रोदय",
    "book.caitanya-carita.title": "चैत्यचरित",
    "book.caitanya-caritamrta-mahakavya.title": "चैत्यचरितामृत महाकाव्य",
    "book.caitanya-caritamrta.title": "चैत्यचरितामृत",
    "book.dana-keli-kaumudi.title": "दानकेलिकौमुदी",
    "book.gita-govinda.title": "गीतगोविन्द",
    "book.gopala-campu.title": "गोपालचम्पू",
    "book.govinda-lilamrta.title": "गोविन्दलीलामृत",
    "book.govinda-rati-manjari.title": "श्रीगोविन्दरतिमञ्जरी",
    "book.govinda-virudavali.title": "गोविन्दविरुदावली",
    "book.jagannatha-vallabha-nataka.title": "जगन्नाथवल्लभनाटक",
    "book.krama-dipika.title": "क्रमदीपिका",
    "book.krsna-bhavanamrta.title": "कृष्णभावनामृत",
    "book.krsna-karnamrta.title": "कृष्णकर्णामृत",
    "book.krsnahnika-kaumudi.title": "कृष्णाह्निककौमुदी",
    "book.kunja-bhanga.title": "कुञ्जभङ्ग",
    "book.lalita-madhava.title": "ललितामाधव",
    "book.padyavali.title": "पद्यावली",
    "book.radha-krsna-ganoddesa-dipika.title": "राधाकृष्णगणोद्देशदीपिका",
    "book.radha-rasa-sudha-nidhi.title": "राधारससुधानिधि",
    "book.sadhanamrta-candrika.title": "साधनामृतचन्द्रिका",
    "book.sangita-madhava.title": "सङ्गीतमाधव",
    "book.stavamala.title": "स्तवमाला",
    "book.stavavali.title": "स्तवावली",
    "book.ujjvala-nilamani.title": "उज्ज्वलनीलमणि",
    "book.vidagdha-madhava.title": "विदग्धमाधव",
    "book.vilapa-kusumanjali.title": "विलापकुसुमाञ्जलि",
    "book.vraja-riti-cintamani.title": "व्रजरीतिचिन्तामणि",
    "book.vrndavana-mahimamrta.title": "वृन्दावनमहिमामृत",

    # Common UI
    "common.bookmark.add": "इस अनुभाग को बुकमार्क करें",
    "common.bookmark.remove": "बुकमार्क हटाएँ",
    "common.done": "हो गया",
    "common.menu": "मेनू",
    "common.next": "अगला",
    "common.periods": "समय अवधि",
    "common.previous": "पिछला",
    "common.quote.few": "श्लोक",
    "common.quote.many": "श्लोक",
    "common.quote.one": "श्लोक",
    "common.quote.other": "श्लोक",
    "common.reset": "पुनर्स्थापित करें",
    "common.scriptures": "उद्धृत ग्रन्थ",
    "common.settings": "सेटिंग्स",

    # Font
    "font.sans": "सैन्स",
    "font.serif": "सेरिफ",

    # Language
    "language.english": "English",
    "language.russian": "Русский",

    # Menu
    "menu.bookmarks": "बुकमार्क",
    "menu.fontFamily": "फ़ॉन्ट",
    "menu.language": "भाषा",
    "menu.share": "साझा करें",
    "menu.textSize": "टेक्स्ट आकार",
    "menu.theme": "थीम",

    # Period names
    "period.aparahna.name": "अपराह्न लीला",
    "period.madhyahna.name": "मध्याह्न लीला",
    "period.nisha.name": "निशा लीला",
    "period.nishanta.name": "निशान्त लीला",
    "period.pradosha.name": "प्रदोष लीला",
    "period.pratah.name": "प्रातः लीला",
    "period.purvahna.name": "पूर्वाह्न लीला",
    "period.sayahna.name": "सायाह्न लीला",

    # Period node names (same as period names)
    "period_node.aparahna_1.name": "अपराह्न लीला",
    "period_node.aparahna_2.name": "अपराह्न लीला",
    "period_node.aparahna_3.name": "अपराह्न लीला",
    "period_node.aparahna_4.name": "अपराह्न लीला",
    "period_node.madhyahna_1.name": "मध्याह्न लीला",
    "period_node.madhyahna_10.name": "मध्याह्न लीला",
    "period_node.madhyahna_11.name": "मध्याह्न लीला",
    "period_node.madhyahna_2.name": "मध्याह्न लीला",
    "period_node.madhyahna_3.name": "मध्याह्न लीला",
    "period_node.madhyahna_4.name": "मध्याह्न लीला",
    "period_node.madhyahna_5.name": "मध्याह्न लीला",
    "period_node.madhyahna_6.name": "मध्याह्न लीला",
    "period_node.madhyahna_7.name": "मध्याह्न लीला",
    "period_node.madhyahna_8.name": "मध्याह्न लीला",
    "period_node.madhyahna_9.name": "मध्याह्न लीला",
    "period_node.nisha_1.name": "निशा लीला",
    "period_node.nisha_2.name": "निशा लीला",
    "period_node.nisha_3.name": "निशा लीला",
    "period_node.nisha_4.name": "निशा लीला",
    "period_node.nisha_5.name": "निशा लीला",
    "period_node.nisha_6.name": "निशा लीला",
    "period_node.nisha_7.name": "निशा लीला",
    "period_node.nisha_8.name": "निशा लीला",
    "period_node.nishanta_1.name": "निशान्त लीला",
    "period_node.nishanta_2.name": "निशान्त लीला",
    "period_node.nishanta_3.name": "निशान्त लीला",
    "period_node.pradosha_1.name": "प्रदोष लीला",
    "period_node.pradosha_2.name": "प्रदोष लीला",
    "period_node.pradosha_3.name": "प्रदोष लीला",
    "period_node.pradosha_4.name": "प्रदोष लीला",
    "period_node.pratah_1.name": "प्रातः लीला",
    "period_node.pratah_2.name": "प्रातः लीला",
    "period_node.pratah_3.name": "प्रातः लीला",
    "period_node.pratah_4.name": "प्रातः लीला",
    "period_node.purvahna_1.name": "पूर्वाह्न लीला",
    "period_node.purvahna_2.name": "पूर्वाह्न लीला",
    "period_node.purvahna_3.name": "पूर्वाह्न लीला",
    "period_node.sayahna_1.name": "सायाह्न लीला",
    "period_node.sayahna_2.name": "सायाह्न लीला",
    "period_node.sayahna_3.name": "सायाह्न लीला",

    # Danda descriptions
    "period.danda.1.desc": "ये कुछ सखियाँ दम्पति को आलिंगन में सोए हुए देखकर आनन्दित होती हैं।",
    "period.danda.2.desc": "इस विश्राम काल में वे स्वप्न में मिलते हैं और अपार लीलाओं का आनन्द लेते हैं।",
    "period.danda.3.desc": "वे जागते हैं, उनकी सुन्दरता देखते हैं, आकर्षित होते हैं... किन्तु वे उठती हैं और प्रेमयुद्ध होता है।",
    "period.danda.4.desc": "वे पुनः सोते हैं, पक्षी जागकर गाते हैं; अब सखियाँ उठकर उनकी कुञ्ज में आती हैं।",
    "period.danda.5.desc": "प्रभात होते ही रूपामञ्जरी प्रवेश करती है और सोई हुई राधा के चरण पकड़कर जगाती है।",
    "period.danda.6.desc": "हाथ पकड़कर वे बाहर निकलते हैं, सखियाँ सान्त्वना देकर उन्हें घर भेजती हैं।",
    "period.danda.7.desc": "राधा और कृष्ण अपने-अपने घर में बड़ों द्वारा जगाए जाते हैं।",
    "period.danda.8.desc": "कृष्ण गाएँ दुहने जाते हैं, फिर यमुना के पास; वे स्नान करके पहनती हैं और यमुना जाती हैं।",
    "period.danda.9.desc": "वे साथ में जल में खेलते हैं, सखियाँ उन्हें सुखाकर पहनाती हैं।",
    "period.danda.10.desc": "सखियाँ राधा-श्याम को भोजन कराती हैं, सब शीघ्र घर लौटते हैं।",
    "period.danda.11.desc": "यशोदा कुण्डलता को राधा को बुलाने भेजती हैं; राधा जटिला से अनुमति लेकर जाती हैं।",
    "period.danda.12.desc": "वे सखियों के साथ नन्दग्राम जाती हैं और कृष्ण सम्बन्धी विभिन्न अवस्थाओं का अनुभव करती हैं।",
    "period.danda.13.desc": "राधा को यशोदा प्रेम से ग्रहण करती हैं, राधा रोहिणी के साथ भोजन बनाने रसोई में प्रवेश करती हैं।",
    "period.danda.14.desc": "कृष्ण स्नान करते हैं, वस्त्र धारण करते हैं, मित्रों के साथ भोजन करते हैं।",
    "period.danda.15.desc": "राधा और उनकी सखियाँ लज्जा से कृष्ण के अवशिष्ट भोजन का स्वाद लेती हैं।",
    "period.danda.16.desc": "कृष्ण गायों को चराने के लिए सजते हैं; यशोदा उन्हें राधा के चरणों में झुकाती हैं।",
    "period.danda.17.desc": "कृष्ण मित्रों सहित वन की ओर प्रस्थान करते हैं; सब नगरवासी उन्हें विदा करते हैं।",
    "period.danda.18.desc": "राधा और उनकी सखियाँ सूर्यदेव की पूजा की तैयारी करती हैं।",
    "period.danda.19.desc": "राधा पूजा की सामग्री सूर्य मन्दिर में रखकर चिन्तित होकर राधाकुण्ड जाती हैं।",
    "period.danda.20.desc": "मित्रों के साथ थोड़ा खेलने के बाद कृष्ण चुपके से निकलकर राधाकुण्ड जाते हैं।",
    "period.danda.21.desc": "तट पर पहुँचकर वे गुप्त रूप से उनकी सुन्दरता देखते हैं और प्रेम से व्याकुल हो जाते हैं।",
    "period.danda.22.desc": "वे उनकी सुन्दरता देखकर सखियों से पूछती हैं कि क्या वे मेघ हैं या स्वयं मन्मथ।",
    "period.danda.23.desc": "वन के कथित स्वामित्व पर बहस होती है; ललिता उन्हें डाँटती हैं।",
    "period.danda.24.desc": "आनन्ददायक झूले, बाँसुरी चोरी, रंगीन जल से खेल, वन में भ्रमण।",
    "period.danda.25.desc": "राधा और कृष्ण कुञ्ज में प्रवेश करके श्रृंगारलीला करते हैं।",
    "period.danda.26.desc": "दासियाँ सामग्री एकत्र करके उनकी पूजा करती हैं जब वे कुञ्ज से बाहर आते हैं।",
    "period.danda.27.desc": "मित्रों द्वारा सेवित, वे जलक्रीड़ा, श्रृंगार, वनभोज और पासे का खेल आरम्भ करते हैं।",
    "period.danda.28.desc": "वे मधुपान का आनन्द लेते हैं; अवर्णनीय उन्मत्त लीलाएँ होती हैं।",
    "period.danda.29.desc": "अधिक जलक्रीड़ा, फिर सूखे वस्त्र; वे पक्षियों की वाचन सुनते हैं फिर विश्राम करते हैं।",
    "period.danda.30.desc": "वे रत्नासन पर बैठकर हँसी-मजाक करते हैं, घर लौटने का समय होने पर दुःखित होते हैं।",
    "period.danda.31.desc": "राधा सूर्य मन्दिर जाती हैं; कृष्ण मित्रों से मिलकर सूर्य मन्दिर जाते हैं।",
    "period.danda.32.desc": "कृष्ण पुजारी का वेश धारण करके हास्यपूर्ण व्यंग्यों से कपटपूर्ण पूजा करते हैं।",
    "period.danda.33.desc": "वे घर लौटकर विश्राम करती हैं, वे ग्वालबाल मित्रों से मिलकर अनेक खेल खेलते हैं।",
    "period.danda.34.desc": "कृष्ण गायों को लेकर व्रज की ओर जाते हैं, राधा के निवास के पास से गुजरते हैं।",
    "period.danda.35.desc": "सब नगरवासी कृष्ण का अभिवादन करने बाहर आते हैं; राधा उनसे तड़पती दृष्टि से मिलती हैं।",
    "period.danda.36.desc": "कृष्ण गायें दुहने जाते हैं, परन्तु राधा के साथ भोजन करते हैं; फिर गायें दुहते हैं।",
    "period.danda.37.desc": "यशोदा और रोहिणी कृष्ण-बलराम की आरती करती हैं; राधा आरती करके भोजन भेजती हैं।",
    "period.danda.38.desc": "नन्द घर आते हैं, कृष्ण को स्नेह करते हैं और सैकड़ों दूध के घड़ों के परिवहन का निरीक्षण करते हैं।",
    "period.danda.39.desc": "नन्द, कृष्ण और बलराम सायंकालीन भोजन ग्रहण करते हैं; यशोदा राधा द्वारा भेजे गए भोजन परोसती हैं।",
    "period.danda.40.desc": "अधिक भोजन-आनन्द; वे समाप्त करके स्नान करते हैं और यशोदा धनिष्ठा द्वारा अवशिष्ट राधा को भेजती हैं।",
    "period.danda.41.desc": "कृष्ण को बाद में गुप्त मिलन की योजना का पता चलता है; धनिष्ठा राधा और सखियों को प्रसाद लाती है।",
    "period.danda.42.desc": "भोजन के बाद कृष्ण विश्राम करते हैं, फिर नन्द की सभा में जाते हैं; राधा भोजन समाप्त करके विश्राम करती हैं।",
    "period.danda.43.desc": "कृष्ण प्रदर्शन और वाचन का आनन्द लेते हैं, फिर यशोदा उन्हें शयन के लिए बुलाती हैं।",
    "period.danda.44.desc": "थोड़ा विश्राम करके वे महान व्याकुलता से चुपके से निकलकर नियत कुञ्ज में जाते हैं।",
    "period.danda.45.desc": "राधा उठती हैं, स्नान करके सुन्दर श्रृंगार करती हैं, फिर चिन्तित होकर वृन्दा के पास दूत भेजती हैं।",
    "period.danda.46.desc": "दूत की सहायता से राधा अपनी सखियों सहित मिलन स्थल की ओर प्रस्थान करती हैं।",
    "period.danda.47.desc": "वे यमुना तट पर कुञ्ज में पहुँचकर भीतर प्रतीक्षा करती हैं; कृष्ण निकट आते हैं।",
    "period.danda.48.desc": "वे आकर प्रवेश करते हैं; सब आनन्दित होते हैं, वे गाते हुए वन में भ्रमण करते हैं।",
    "period.danda.49.desc": "सखियाँ उन्हें पंखा झलती हैं जब वे एक-दूसरे की गोद में बैठकर गोपनीय प्रेम-विषयों पर चर्चा करते हैं।",
    "period.danda.50.desc": "वे नृत्य आरम्भ करने की आज्ञा देते हैं, और सब गान और वाद्य बजाकर साथ देते हैं।",
    "period.danda.51.desc": "रासलीला वृत्ताकार श्रेणियों, अद्भुत गतियों और प्रचुर संगीत से खिल उठती है।",
    "period.danda.52.desc": "वे थोड़ा विश्राम करते हैं और शीतल पुष्पों से सजाए जाते हैं, फिर पेय से ताजगी दी जाती है।",
    "period.danda.53.desc": "शयन श्रृंगार लीलाएँ, मधुपान, यमुना जलक्रीड़ा, नूतन वस्त्र, भोजन और विश्राम।",
    "period.danda.54.desc": "वे दोनों समस्त लज्जा त्यागकर आमने-सामने अपनी समस्त कामलीलाएँ करते हैं।",
    "period.danda.55.desc": "वे कुञ्ज से बाहर निकलकर थोड़ा विश्राम करते हैं, फिर पुनः प्रवेश करते हैं जहाँ वे उन्हें आभूषणों से सजाते हैं।",
    "period.danda.56.desc": "वे उन्हें आज्ञा देती हैं कि एक-एक करके समस्त कुञ्जों में जाकर उनकी सब सखियों के दर्शन करें।",
    "period.danda.57.desc": "वे प्रसन्नता से उनकी कुञ्ज में लौटते हैं; उन्हें निद्रित देखकर चुपके से प्रवेश करके क्रीड़ापूर्वक उन पर आक्रमण करते हैं।",
    "period.danda.58.desc": "वे चौंकती हैं; वे पुनः अपनी इच्छाएँ पूरी करते हैं, फिर मधुपान करके और अधिक विश्राम करते हैं।",
    "period.danda.59.desc": "सखियाँ अब प्रवेश करती हैं और उनके चरणों की सुखद मालिश करती हैं जब वे आनन्दपूर्ण शयन में लीन होते हैं।",
    "period.danda.60.desc": "रात्रि के अन्तिम प्रहर में कुछ कन्याएँ अपनी-अपनी कुञ्जों में विश्राम को जाती हैं, कुछ जागरण में रहती हैं।",
}

# Period info
for i in range(1, 61):
    HI_TRANSLATIONS[f"period.danda.{i}.desc"] = HI_TRANSLATIONS.get(f"period.danda.{i}.desc", "")

# Period info UI
HI_TRANSLATIONS.update({
    "period.ghatika.count": "घटिका {count} / 60",
    "period.info.countdown.hm": "{h}घ {m}मि",
    "period.info.countdown.m": "{m}मि",
    "period.info.current": "वर्तमान अवधि",
    "period.info.currentSub": "वर्तमान उप-अवधि",
    "period.info.next": "अगला: {title}",
    "period.info.nextIn": "अगला: {title} — {countdown} में",
})

# Section titles
HI_TRANSLATIONS.update({
    "section.aparahna_1.1.title": "चन्दनकला सखी राधा को शान्ति देती हैं",
    "section.aparahna_2.1.title": "राधा कृष्ण के प्रिय पाँच मिष्टान बनाती हैं",
    "section.aparahna_3.1.title": "राधा कृष्ण की बाँसुरी की स्तुति करती हैं",
    "section.aparahna_4.1.title": "सखियाँ लौटते हुए कृष्ण का स्वागत करती हैं",
    "section.aparahna_4.2.title": "राधा-माधव का मिलन",
    "section.madhyahna_1.1.title": "कृष्ण के प्रति राधा का आकर्षण",
    "section.madhyahna_1.2.title": "कृष्ण की बाँसुरी की शक्ति",
    "section.madhyahna_1.3.title": "तुलसीमञ्जरी कृष्ण की समाचार लाती हैं",
    "section.madhyahna_1.4.title": "धनिष्ठा वसन्त की सुन्दरता का वर्णन करती हैं",
    "section.madhyahna_1.5.title": "कृष्ण की ओर प्रेमयात्रा",
    "section.madhyahna_1.6.title": "कृष्ण वृन्दा को राधा को लाने भेजते हैं",
    "section.madhyahna_1.7.title": "राधा, वृन्दा और कुण्डलता की चर्चा",
    "section.madhyahna_1.8.title": "राधा-गोविन्द का परस्पर दर्शन",
    "section.madhyahna_1.9.title": "राधा से मिलन पर कृष्ण का आनन्द",
    "section.madhyahna_10.1.title": "पपोगा कृष्ण के दिव्य गुणों का वर्णन करते हैं",
    "section.madhyahna_11.1.title": "माद्य पपोगा सखियों का वर्णन करती हैं",
    "section.madhyahna_11.2.title": "जुआ खेल",
    "section.madhyahna_11.3.title": "सूर्यदेव की पूजा",
    "section.madhyahna_2.1.title": "पुष्प संग्रह के समय वार्ता",
    "section.madhyahna_2.2.title": "वन पर राधा का अधिकार",
    "section.madhyahna_2.3.title": "चतुर संवाद",
    "section.madhyahna_2.4.title": "कृष्ण राधा को आलिंगत करते हैं",
    "section.madhyahna_2.5.title": "ललिता कृष्ण से हँसी-मजाक करती हैं",
    "section.madhyahna_3.1.title": "बाँसुरी चोरी की लीलाएँ",
    "section.madhyahna_3.2.title": "कृष्ण राधा की कुञ्ज में प्रवेश करते हैं",
    "section.madhyahna_3.3.title": "कृष्ण का कुञ्ज में प्रवेश और विविध विलास",
    "section.madhyahna_4.1.title": "राधा का वर्णन",
    "section.madhyahna_4.2.title": "षडृतुओं की सेवा का वर्णन",
    "section.madhyahna_4.3.title": "वृन्दावन की शोभा वर्णन",
    "section.madhyahna_5.1.title": "छह ऋतुओं की सेवा",
    "section.madhyahna_5.2.title": "वृन्दावन की सुन्दरता",
    "section.madhyahna_5.3.title": "लताओं की सेवा",
    "section.madhyahna_5.4.title": "राधा का क्रोध का अभिनय",
    "section.madhyahna_5.5.title": "वसन्त वन",
    "section.madhyahna_6.1.title": "वसन्त होली पर्व",
    "section.madhyahna_6.2.title": "ग्रीष्मकालीन वन लीलाएँ",
    "section.madhyahna_6.3.title": "वर्षाकालीन वन में प्रवेश",
    "section.madhyahna_6.4.title": "झूले की लीलाएँ",
    "section.madhyahna_6.5.title": "शरद ऋतु का वन",
    "section.madhyahna_6.6.title": "शीत ऋतु का वन",
    "section.madhyahna_6.7.title": "हेमन्त ऋतु का वन",
    "section.madhyahna_6.8.title": "प्रेम में राधा के रूपान्तरण",
    "section.madhyahna_7.1.title": "शयन लीलाएँ",
    "section.madhyahna_7.2.title": "राधा की अन्तरंगता पर चर्चा",
    "section.madhyahna_7.3.title": "ललितानन्दकुञ्ज में मधुपान लीला",
    "section.madhyahna_8.1.title": "राधाकुण्ड में दिव्य जलक्रीड़ा",
    "section.madhyahna_8.2.title": "कमल मण्डप में श्रृंगार",
    "section.madhyahna_8.3.title": "वन में भोज",
    "section.madhyahna_9.1.title": "पपोगा कृष्ण के सुन्दर विग्रह की स्तुति करते हैं",
    "section.madhyahna_10.2.title": "निरुपम सुन्दर युगल की तुलना किससे?",
    "section.madhyahna_10.3.title": "मुखमण्डल की उपमा किससे?",
    "section.madhyahna_9.2.title": "उनके गुणों की गणना कौन कर सकता है?",
    "section.madhyahna_9.3.title": "श्रीराधारानी का रूप वर्णन",
    "section.nisha_1.1.title": "वृन्दा राधा-माधव की सेवा करती हैं",
    "section.nisha_1.2.title": "वन में लीलाएँ",
    "section.nisha_1.3.title": "वन की महिमा",
    "section.nisha_2.1.title": "रासलीला आरम्भ",
    "section.nisha_2.2.title": "रासलीला",
    "section.nisha_3.1.title": "विश्राम और पुनः नृत्य",
    "section.nisha_4.1.title": "मधुपान",
    "section.nisha_4.2.title": "राधा-माधव की अन्तरंग लीलाएँ",
    "section.nisha_4.3.title": "अन्य गोपियों के साथ लीलाएँ",
    "section.nisha_5.1.title": "जललीला",
    "section.nisha_6.1.title": "श्रृंगार, भोजन और विश्राम",
    "section.nisha_7.1.title": "मञ्जरियाँ राधा-माधव की सेवा करती हैं",
    "section.nisha_8.1.title": "राधा-माधव की गोपनीय लीलाएँ",
    "section.nisha_8.2.title": "माधव अन्य गोपियों का आनन्द लेते हैं",
    "section.nishanta_1.1.title": "सखियों की प्रातः सेवाएँ",
    "section.nishanta_1.2.title": "पक्षी राधा और कृष्ण को जगाते हैं",
    "section.nishanta_1.3.title": "क्रीड़ा-श्रम",
    "section.nishanta_1.4.title": "राधा-कृष्ण की मधुर थकान",
    "section.nishanta_1.5.title": "युगल का रसालस-माधुरी-आस्वादन और विलास",
    "section.nishanta_1.6.title": "देवता की सेवा में लगता हूँ",
    "section.nishanta_1.7.title": "श्रीराधा की वेश-रचना में नियुक्त श्रीकृष्ण को मदनावेश",
    "section.nishanta_2.1.title": "मञ्जरियों की सेवा और कृष्ण की व्याकुलता",
    "section.nishanta_2.2.title": "माद्य पपोगा राधा से बात करती हैं",
    "section.nishanta_2.3.title": "नर पपोगा कृष्ण से बात करते हैं",
    "section.nishanta_2.4.title": "श्रीराधा और शय्या देखकर सखियों का आनन्द",
    "section.nishanta_2.5.title": "कुञ्ज द्वारा सखियों का तत्कालिक शोभादर्शन",
    "section.nishanta_2.6.title": "पक्षी-कलरव से निद्रा-भंग",
    "section.nishanta_2.7.title": "सुरतशय्या और श्रीराधांग-दर्शन से सखियों को परमानन्द",
    "section.nishanta_3.1.title": "घर जाना भूलना और कक्खटी का पद्यपाठ",
    "section.nishanta_3.2.title": "राधा का विलाप और शयन",
    "section.nishanta_3.3.title": "ललिता द्वारा प्रभात वर्णन",
    "section.nishanta_3.4.title": "गृह गमन-विस्मृति और कक्खटी का पद्यपाठ",
    "section.nishanta_3.5.title": "युगल के स्वगृहयात्रा-प्रकार",
    "section.nishanta_3.6.title": "श्रीराधा का आक्षेपादि और शयन",
    "section.pradosha_1.1.title": "इन्दुप्रभा सखी राधा को कृष्ण का समाचार लाती हैं",
    "section.pradosha_1.2.title": "कृष्ण का शयनकक्ष",
    "section.pradosha_1.3.title": "कृष्ण राधा की सुन्दरता का वर्णन करते हैं",
    "section.pradosha_1.4.title": "सुबल राधा की विरह का वर्णन करता है",
    "section.pradosha_1.5.title": "नन्द कृष्ण का मनोरंजन करते हैं",
    "section.pradosha_2.1.title": "कृष्ण अपने शयनकक्ष में जाते हैं",
    "section.pradosha_2.2.title": "राधा की सायंकालीन भोज",
    "section.pradosha_3.1.title": "कृष्ण राधा से मिलने जाते हैं",
    "section.pradosha_3.2.title": "राधा कृष्ण की सुन्दरता का वर्णन करती हैं",
    "section.pradosha_3.3.title": "ललिता राधा को सान्त्वना देती हैं और वे प्रस्थान करती हैं",
    "section.pradosha_3.4.title": "गोविन्दस्थल का वर्णन",
    "section.pradosha_4.1.title": "कृष्ण से मिलन",
    "section.pradosha_4.2.title": "कृष्ण राधा को खोजते हैं",
    "section.pratah_1.1.title": "मञ्जरियों की क्रियाएँ और राधा का निवास",
    "section.pratah_1.2.title": "राधा की सेवा करना",
    "section.pratah_1.3.title": "प्रभात और मुखरा का आगमन",
    "section.pratah_1.4.title": "राधा जागती हैं",
    "section.pratah_1.5.title": "श्यामला सखी से वार्ता",
    "section.pratah_1.6.title": "मधुरिका कृष्ण के जागने और गाय दुहने का वर्णन करती हैं",
    "section.pratah_1.7.title": "गायों का दुहना",
    "section.pratah_1.8.title": "राधा की अवस्था और श्यामला का प्रस्थान",
    "section.pratah_1.9.title": "राधा दाँत माँजती हैं",
    "section.pratah_2.1.title": "राधा का स्नान और श्रृंगार",
    "section.pratah_2.2.title": "कृष्ण की गोदोहन लीला एवं रहस्यालाप",
    "section.pratah_2.3.title": "भवन के द्वार पर आगमन",
    "section.pratah_2.4.title": "राधारानी की तत्कालीन अवस्था एवं श्यामला का गृहगमन",
    "section.pratah_2.5.title": "राधिका दन्तधावनादि लीला",
    "section.pratah_3.1.title": "हिरण्याङ्गी सखी कृष्ण के कुस्ती और स्नान का वर्णन करती हैं",
    "section.pratah_3.2.title": "कृष्ण के वस्त्र और आभूषण",
    "section.pratah_3.3.title": "कुण्डलता राधा को नन्द के घर ले जाती है",
    "section.pratah_3.4.title": "सखियों के साथ हँसी-मजाक",
    "section.pratah_3.5.title": "तुङ्गविद्या नन्दीश्वर का वर्णन करती हैं",
    "section.pratah_3.6.title": "प्रवेश द्वार पर कृष्ण के दर्शन",
    "section.pratah_3.7.title": "राधा यशोदा से मिलती हैं",
    "section.pratah_3.8.title": "यशोदा के भोजन निर्देश",
    "section.pratah_3.9.title": "राधा और रोहिणी भोजन बनाती हैं",
    "section.pratah_3.10.title": "यशोदा तैयारियों का निरीक्षण करती हैं",
    "section.pratah_4.1.title": "भोजन परोसना और भोजन",
    "section.pratah_4.2.title": "नाश्ते में हँसी-मजाक",
    "section.pratah_4.3.title": "राधा को देखकर कृष्ण की भूख शान्त होती है",
    "section.pratah_4.4.title": "सखियाँ भोजन ग्रहण करती हैं",
    "section.purvahna_1.1.title": "कृष्ण का श्रृंगार और मित्रों से मिलना",
    "section.purvahna_1.2.title": "वन खेल की सामग्री",
    "section.purvahna_1.3.title": "कृष्ण के प्रस्थान पर गोपियों की प्रतिक्रिया",
    "section.purvahna_1.4.title": "यशोदा कृष्ण को निर्देश देती हैं",
    "section.purvahna_1.5.title": "व्रजवासियों से विदाई",
    "section.purvahna_1.6.title": "राधा कृष्ण से मिलन की योजना बनाती हैं",
    "section.purvahna_2.1.title": "कृष्ण और उनके मित्रों का वर्णन",
    "section.purvahna_2.2.title": "वृन्दावन वन और बालकों की लीलाएँ",
    "section.purvahna_2.3.title": "वन कृष्ण का स्वागत करता है",
    "section.purvahna_2.4.title": "कृष्ण हर स्थान पर राधा को देखते हैं",
    "section.purvahna_2.5.title": "धनिष्ठा का समाचार और कृष्ण की जलक्रीड़ा",
    "section.purvahna_2.6.title": "पिकनिक और कुसुम सरोवर पर मिलन",
    "section.purvahna_2.7.title": "तुलसी राधा का समाचार लाती हैं",
    "section.purvahna_2.8.title": "धोखे में सखी शैब्या",
    "section.purvahna_3.1.title": "रूपामञ्जरी राधा की व्यथा का वर्णन करती हैं",
    "section.purvahna_3.2.title": "राधा राधाकुण्ड जाती हैं",
    "section.purvahna_3.3.title": "ललितानन्दकुञ्ज का वर्णन",
    "section.sayahna_1.1.title": "कृष्ण के आकर्षक गुण",
    "section.sayahna_1.2.title": "तुलसी राधिका को शान्ति देती हैं",
    "section.sayahna_1.3.title": "यशोदा का कृष्ण पर स्नेह",
    "section.sayahna_2.1.title": "कृष्ण का स्नान",
    "section.sayahna_2.2.title": "कृष्ण और बलराम का भोजन",
    "section.sayahna_3.1.title": "कृष्ण गायें दुहते हैं",

    # Common UI continued
    "sample.readingText": "कृष्ण सखियों सहित कुञ्ज से बाहर निकले।",
    "screen.book_reader.empty": "इस पुस्तक के सम्पूर्ण पाठ धीरे-धीरे जोड़े जा रहे हैं।",
    "screen.bookmarks.empty": "अभी कोई बुकमार्क नहीं। पढ़ते समय बुकमार्क आइकन दबाकर अनुभाग सहेजें।",
    "screen.books.empty": "कोई ग्रन्थ नहीं मिला।",
    "screen.books.title": "मूल ग्रन्थ",
    "screen.hindi.empty": "इस भाषा में हिन्दी अनुभाग उपलब्ध नहीं हैं।",
    "screen.hindi.verse.one": "श्लोक",
    "screen.hindi.verse.other": "श्लोक",
    "screen.home.title": "अष्टकालीय लीला",
    "screen.periods.empty": "अभी अवधि विवरण नहीं हैं।",
    "screen.periods.title": "दिन की अवधियाँ",
    "screen.search.empty": "सभी श्लोकों, विषय शीर्षकों और उद्धृत ग्रन्थों में खोजें। दीर्घचिह्न वैकल्पिक हैं — \"krishna\" से \"कृष्ण\" मिलेगा।",
    "screen.search.hint": "श्लोक, विषय, ग्रन्थ खोजें...",
    "screen.search.noResults": "कोई परिणाम नहीं मिला।",
    "screen.search.submit": "खोजें",
    "screen.verse.empty": "श्लोक नहीं मिला।",
    "screen.verse.title": "श्लोक",
    "theme.darkOak": "गहरा (ओक)",
    "theme.followSystem": "सिस्टम के अनुसार",
    "theme.lightParchment": "हल्का (पर्चमेन्ट)",
})

db = r'C:\Users\austr\bss\assets\db\Bhavanasara-Sangraha.sqlite'
conn = sqlite3.connect(db)
c = conn.cursor()

updated = 0
skipped = 0
not_found = 0

for key, hi_text in sorted(HI_TRANSLATIONS.items()):
    if not hi_text:
        skipped += 1
        continue
    c.execute("SELECT hi FROM translations WHERE translation_key = ?", (key,))
    row = c.fetchone()
    if not row:
        not_found += 1
        continue
    if row[0]:
        continue
    c.execute("UPDATE translations SET hi = ? WHERE translation_key = ?", (hi_text, key))
    updated += 1

conn.commit()

c.execute("SELECT COUNT(*) FROM translations WHERE hi IS NOT NULL AND hi != ''")
hi_count = c.fetchone()[0]
c.execute("SELECT COUNT(*) FROM translations")
total = c.fetchone()[0]

print(f"Updated: {updated}")
print(f"Skipped (empty): {skipped}")
print(f"Not found in DB: {not_found}")
print(f"Total with HI: {hi_count}/{total}")

conn.close()
print("\nDone.")
